french_flashcards:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres  # Docker service name
      user: news_user
      password: dev_password_123
      port: 5432
      dbname: french_news
      schema: dbt_staging
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      search_path: "dbt_staging"