services:
  postgres-dev:
    image: postgres:17-alpine
    container_name: french_news_dev_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-test:
    image: postgres:17-alpine
    container_name: french_news_test_db
    environment:
      POSTGRES_DB: french_news_test
      POSTGRES_USER: news_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data  # Fast in-memory
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U news_user -d french_news_test"]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  postgres_dev_data: