services:
  postgres:
    image: postgres:17-alpine
    container_name: french_news_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: french_news
      POSTGRES_USER: news_user
      POSTGRES_PASSWORD: dev_password_123
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U news_user -d french_news"]
      interval: 10s
      timeout: 5s
      retries: 5

  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper
    container_name: french_news_scraper
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_ENABLED=true
      - OFFLINE=true
      - DEBUG=true
      - DB_HOST=postgres
    volumes:
      - ./src:/app/src  # Mount source for development
    profiles: ["scraper"]

  dbt:
    build:
      context: .
      dockerfile: Dockerfile.dbt
    container_name: french_news_dbt
    depends_on:
      postgres:
        condition: service_healthy
    profiles: ["dbt"]

volumes:
  postgres_data:
    driver: local