french_flashcards:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: news_user
      password: dev_password_123
      port: 5432
      dbname: french_news
      schema: dbt_staging
      threads: 4
    test:
      type: postgres
      host: localhost
      user: news_user
      password: dev_password_123
      port: 5432
      dbname: french_news
      schema: dbt_test
      threads: 4
    prod:
      type: postgres
      host: localhost
      user: news_user
      password: dev_password_123
      port: 5432
      dbname: french_news
      schema: dbt_prod
      threads: 4