version: 2

sources:
  - name: news_data
    schema: "{{ 'news_data_test' if target.name == 'test' else 'news_data_dev' }}"
    tables:
      - name: articles
        description: Raw scraped French articles
        columns:
          - name: id
            tests:
              - unique
              - not_null
          - name: url
            tests:
              - not_null
          - name: title
            tests:
              - not_null
          - name: full_text
            tests:
              - not_null
          - name: article_date
          - name: source_name