version: 2

sources:
  - name: news_data
    schema: "{{ 'news_data_test' if target.name == 'test' else 'news_data_dev' }}"
    tables:
      - name: raw_articles
        description: Raw scraped data (pure ELT - includes duplicates)
        columns:
          - name: id
            tests:
              - not_null
          - name: url
            tests:
              - not_null
          - name: raw_html
            tests:
              - not_null
          - name: source
            tests:
              - not_null
          - name: scraped_at
          - name: response_status
          - name: content_length