name: CI - Run Tests

# Trigger on every push to any branch and all PRs
on:
  push:
    branches: ['**']
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      # 1. Check out code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # 3. Create venv and install dependencies
      - name: Create venv and install dependencies
        run: |
          python -m venv venv
          ./venv/bin/pip install --upgrade pip
          ./venv/bin/pip install -e .[dev]

      # 4. Start PostgreSQL test database
      - name: Start test database
        run: make db-start ENV=test

      # 5. Run linter
      - name: Lint code
        run: make lint
        continue-on-error: true  # Don't fail on lint warnings

      # 6. Run tests
      - name: Run tests
        run: make test

      # 7. Stop database (cleanup)
      - name: Stop database
        if: always()
        run: make db-stop

      # 8. Upload test results (optional)
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: .pytest_cache/